# Generated by Django 4.0.5 on 2022-06-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('device_id', models.CharField(max_length=255, null=True)),
                ('device_token', models.CharField(max_length=255, null=True)),
                ('device_model', models.CharField(max_length=255, null=True)),
                ('user_agent', models.TextField(null=True)),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('deactivated_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
