# Generated by Django 4.0.5 on 2022-06-27 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_alter_follower_author_alter_user_created_at_and_more'),
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivation',
            name='author',
            field=models.ForeignKey(db_column='author_id', db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_activation_fk_author', to='user_account.user', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdevicetoken',
            name='author',
            field=models.ForeignKey(db_column='author_id', db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_device_token_fk_author', to='user_account.user', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdevicetoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userdevicetoken',
            name='deactivated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdevicetoken',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdevicetoken',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdevicetoken',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
