# Generated by Django 4.0.5 on 2022-07-04 03:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oauth', '0003_alter_resetpassword_active_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resetpassword',
            unique_together={('author', 'token')},
        ),
        migrations.AlterUniqueTogether(
            name='useractivation',
            unique_together={('author', 'token')},
        ),
        migrations.AlterUniqueTogether(
            name='userdevicetoken',
            unique_together={('author', 'token')},
        ),
    ]
