# Generated by Django 4.0.5 on 2022-07-06 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oauth', '0004_alter_resetpassword_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='author',
            field=models.ForeignKey(db_column='author_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='reset_password_fk_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='author',
            field=models.ForeignKey(db_column='author_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_activation_fk_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userdevicetoken',
            name='author',
            field=models.ForeignKey(db_column='author_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_device_token_fk_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdevicetoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
