# Generated by Django 4.0.5 on 2022-06-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('subject', models.TextField()),
                ('content', models.TextField()),
                ('is_success', models.BooleanField()),
                ('sended_at', models.DateTimeField(null=True)),
                ('is_seen', models.BooleanField()),
            ],
        ),
    ]
