# Generated by Django 4.0.5 on 2022-07-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_author_alter_notification_sended_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
