# Generated by Django 4.0.5 on 2022-07-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_is_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.TextField(choices=[('BLOG_LIKED', 'Blog Liked'), ('FOLLOWER_NEW_POST', 'Follower New Post')], default='BLOG_LIKED'),
        ),
    ]
