# Generated by Django 4.0.5 on 2022-07-12 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_author'),
        ('notification', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='blog',
            field=models.ForeignKey(blank=True, db_column='blog_uid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_fk_blog', to='blog.blog'),
        ),
    ]
