# Generated by Django 4.0.5 on 2022-07-12 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_author'),
        ('notification', '0005_notification_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='blog',
            field=models.ForeignKey(db_column='blog_uid', db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notification_fk_blog', to='blog.blog'),
            preserve_default=False,
        ),
    ]
