# Generated by Django 4.0.5 on 2022-07-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_logs', '0002_emaillogs_author_alter_emaillogs_sended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillogs',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
