# Generated by Django 4.0.5 on 2022-06-27 07:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(db_column='author_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='blog_fk_author', to='user_account.user')),
            ],
        ),
        migrations.CreateModel(
            name='BlogLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(db_column='author_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='bloglike_fk_author', to='user_account.user')),
                ('blog', models.ForeignKey(db_column='blog_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='bloglike_fk_blog', to='blog.blog')),
            ],
            options={
                'unique_together': {('author', 'blog')},
            },
        ),
        migrations.CreateModel(
            name='BlogHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField()),
                ('name', models.TextField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField()),
                ('published_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(db_column='author_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='bloghistory_fk_author', to='user_account.user')),
                ('blog', models.ForeignKey(db_column='blog_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='bloghistory_fk_blog', to='blog.blog')),
            ],
            options={
                'unique_together': {('blog', 'revision')},
            },
        ),
    ]
