# Generated by Django 4.0.5 on 2022-06-27 06:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(db_column='author_id', db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_fk_author', to='user_account.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloghistory',
            name='author',
            field=models.ForeignKey(db_column='author_id', db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bloghistory_fk_author', to='user_account.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloglike',
            name='author',
            field=models.ForeignKey(db_column='author_id', db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bloglike_fk_author', to='user_account.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('3a3e2a0d-ea8f-4845-a655-5d2a194bdfba'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloghistory',
            name='blog',
            field=models.ForeignKey(db_column='blog_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='bloghistory_fk_blog', to='blog.blog'),
        ),
        migrations.AlterField(
            model_name='bloghistory',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloghistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bloghistory',
            name='published_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloghistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloglike',
            name='blog',
            field=models.ForeignKey(db_column='blog_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='bloglike_fk_blog', to='blog.blog'),
        ),
        migrations.AlterField(
            model_name='bloglike',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloglike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bloglike',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bloghistory',
            unique_together={('blog', 'revision')},
        ),
        migrations.AlterUniqueTogether(
            name='bloglike',
            unique_together={('author', 'blog')},
        ),
    ]
