# Generated by Django 4.0.5 on 2022-06-27 06:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_author_bloghistory_author_bloglike_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b3ddd900-213a-431f-b9eb-2a105d761497'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
