# Generated by Django 4.0.5 on 2022-07-07 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0004_remove_attachment_is_delete_attachment_is_deleted'),
        ('blog', '0003_alter_bloghistory_blog_alter_bloglike_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='attachment',
            field=models.ForeignKey(blank=True, db_column='attachment_uid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_fk_attachment', to='attachment.attachment'),
        ),
    ]
