# Generated by Django 4.0.5 on 2022-07-07 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0004_remove_attachment_is_delete_attachment_is_deleted'),
        ('blog', '0004_blog_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='attachment',
        ),
        migrations.CreateModel(
            name='BlogAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('attachment', models.ForeignKey(db_column='attachment_uid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='blogattachment_fk_attachment', to='attachment.attachment')),
                ('blog', models.ForeignKey(db_column='blog_uid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='blogattachment_fk_blog', to='blog.blog')),
            ],
        ),
    ]
