# Generated by Django 4.0.5 on 2022-07-12 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(db_column='author_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='blog_fk_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
