# Generated by Django 4.0.5 on 2022-06-27 09:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0002_rename_delete_attachment_is_delete'),
        ('blog', '0001_initial'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='follow_by',
            field=models.ForeignKey(blank=True, db_column='follower_by_uid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower_fk_follower_by', to='blog.blog'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(blank=True, db_column='avatar_uid', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_fk_avatar', to='attachment.attachment'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(db_column='follower_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='follower_fk_follower', to='user_account.user'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='OTHER', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('LOCKED', 'Locked'), ('REMOVED', 'Removed')], default='AVAILABLE', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
