# Generated by Django 4.0.5 on 2022-06-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_alter_user_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
