# Generated by Django 4.0.5 on 2022-07-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0010_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
