# Generated by Django 4.0.5 on 2022-07-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0011_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
