# Generated by Django 4.0.5 on 2022-07-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0012_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='admin', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
