# Generated by Django 4.0.5 on 2022-07-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0012_alter_user_username'),
        ('user_account', '0013_user_username'),
    ]

    operations = [
    ]
