# Generated by Django 4.0.5 on 2022-06-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=36)),
                ('type', models.CharField(choices=[('AVA', 'AVATAR'), ('CVR', 'BLOG_COVER')], max_length=32)),
                ('file_name', models.CharField(max_length=225)),
                ('display_name', models.CharField(max_length=225)),
                ('file_path', models.TextField()),
                ('deleted_at', models.DateTimeField(null=True)),
                ('delete', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
