# Generated by Django 4.0.5 on 2022-06-27 07:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('uid', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('AVATAR', 'Ava'), ('BLOG_COVER', 'Cvr')], default='AVATAR', max_length=32)),
                ('file_name', models.CharField(max_length=225)),
                ('display_name', models.CharField(max_length=225)),
                ('file_path', models.TextField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_fk_user', to='user_account.user')),
            ],
        ),
    ]
