# Generated by Django 4.0.5 on 2022-06-27 06:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='id',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uid',
            field=models.CharField(default=uuid.UUID('44f77f1f-c56c-4321-8b25-0c9e978cb296'), editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
