# Generated by Django 4.0.5 on 2022-06-27 04:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_alter_follower_author_alter_user_created_at_and_more'),
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='id',
        ),
        migrations.AddField(
            model_name='attachment',
            name='user',
            field=models.ForeignKey(db_column='user_id', db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attachment_fk_user', to='user_account.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(choices=[('AVATAR', 'Ava'), ('BLOG_COVER', 'Cvr')], default='AVATAR', max_length=32),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uid',
            field=models.CharField(default=uuid.UUID('cf4e5c30-b939-4883-8ac6-fda95ddb216d'), editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
