# Generated by Django 4.0.5 on 2022-06-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='delete',
            new_name='is_delete',
        ),
    ]
