# Generated by Django 4.0.5 on 2022-06-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0002_rename_delete_attachment_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(choices=[('AVATAR', 'Avatar'), ('BLOG_COVER', 'Cover')], default='AVATAR', max_length=32),
        ),
    ]
