# Generated by Django 4.0.5 on 2022-06-27 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_account', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(db_column='author_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='tag_fk_author', to='user_account.user')),
            ],
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('blog', models.ForeignKey(db_column='blog_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='blogtag_fk_blog', to='blog.blog')),
                ('tag', models.ForeignKey(db_column='tag_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='blogtag_fk_tag', to='tag.tag')),
            ],
            options={
                'unique_together': {('blog', 'tag')},
            },
        ),
    ]
