# Generated by Django 4.0.5 on 2022-07-06 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_is_published'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtag',
            name='blog',
            field=models.ForeignKey(db_column='blog_uid', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='blogtag_fk_blog', to='blog.blog'),
        ),
    ]
