# Generated by Django 4.0.5 on 2022-06-27 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
        ('blog', '0002_alter_blog_uid'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtag',
            name='blog',
            field=models.ForeignKey(db_column='blog_id', db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogtag_fk_blog', to='blog.blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='author',
            field=models.ForeignKey(db_column='author_id', db_constraint=False, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tag_fk_author', to='user_account.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='tag',
            field=models.ForeignKey(db_column='tag_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='blogtag_fk_tag', to='tag.tag'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='blogtag',
            unique_together={('blog', 'tag')},
        ),
    ]
