# Generated by Django 4.0.5 on 2022-07-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_alter_blogtag_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='author',
        ),
    ]
